dist: trusty
sudo: required 
language: cpp

services:
  - docker

matrix:
  include:
    - os: linux
      env: IMAGE=fedora:27
    - os: linux
      env: IMAGE=fedora:26
    - os: linux
      env: IMAGE=debian:buster
    - os: linux
      env: IMAGE=ubuntu:artful
    - os: linux
      env: IMAGE=ubuntu:bionic


script: travis_retry tools/one.sh
