dist: xenial
sudo: required 
language: cpp
services:
  - docker

matrix:
  include:
    - os: linux
      env:
        - DOCKER_IMAGE=fedora:29
        - CI=1
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu:bionic
        - CI=1
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu:bionic
        - BUILD_GENERATOR=Ninja
        - CI=1
    - os: linux
      env:
        - DOCKER_IMAGE=centos:7
        - CI=1
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu:xenial
        - CI=1
script:
  - ci/build-in-docker.sh ${DOCKER_IMAGE}
