dist: trusty
sudo: required
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

before_install:
  - sudo apt-get update
  - cd meta && source source_ansible_bash && travis_wait 640 ansible-playbook playbooks/devbox_all.yml && cd ..

script:
  - $TRAVIS_BUILD_DIR/debug
  - $TRAVIS_BUILD_DIR/release
