environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_SYSTEM: bazel
    GENERATOR: Visual Studio 15 2017 Win64
    CONFIG: Release


install:
- IF "%BUILD_SYSTEM%"=="bazel" (
    appveyor DownloadFile https://github.com/bazelbuild/bazel/releases/download/0.14.1/bazel-0.14.1-windows-x86_64.exe -FileName bazel.exe && git submodule update --init --recursive
  )

stack: go 1.10

before_build:
- FOR /f %%i in ('C:\cygwin64\bin\date.exe +%%Y-%%m-%%d') DO SET "RELEASE_DATE=%%i"
- SET "ROOT=%APPVEYOR_BUILD_FOLDER%"

build_script:
- IF "%BUILD_SYSTEM%"=="bazel" (
   %ROOT%\bazel.exe run //:gazelle -- update-repos github.com/cespare/xxhash && %ROOT%\bazel.exe build --verbose_failures --sandbox_debug //src/go/...
  )

test_script:
- IF "%BUILD_SYSTEM%"=="bazel" (
   %ROOT%\bazel.exe test --verbose_failures --sandbox_debug //src/go/...
  )
