environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILD_SYSTEM: bazel
    GENERATOR: Visual Studio 15 2017 Win64
    CONFIG: Release


install:
- appveyor DownloadFile https://github.com/bazelbuild/bazel/releases/download/0.14.1/bazel-0.14.1-windows-x86_64.exe -FileName bazel.exe

before_build:
- FOR /f %%i in ('C:\cygwin64\bin\date.exe +%%Y-%%m-%%d') DO SET "RELEASE_DATE=%%i"
- SET "ROOT=%APPVEYOR_BUILD_FOLDER%"

build_script:
- %ROOT%\bazel.exe build --verbose_failures --sandbox_debug //src/smfc/...
- %ROOT%\bazel.exe build --verbose_failures --sandbox_debug //src/java/...
- %ROOT%\bazel.exe build --verbose_failures --sandbox_debug //src/go/...

test_script:
- %ROOT%\bazel.exe test --verbose_failures --sandbox_debug //src/go/...
