---

- name: Install all dev system tools
  become: yes
  dnf: name='{{item}}'
  with_items:
    - gcc-c++
    - ccache
    - cmake
    - git
    - binutils
    - clang
    - doxygen
    - gtest-devel
