---

- name: Sync soure from git
  git:
    repo='https://github.com/RoaringBitmap/CRoaring.git'
    accept_hostkey=yes
    clone=yes
    dest='{{goobly_cache_dir}}/roaring_bitmap'
    update=yes
    recursive=yes
    version='c97dfc5'
    force=yes

- file:
    path='{{goobly_cache_dir}}/roaring_bitmap/build'
    state=directory

- name: Configure
  shell:
    cmake -DBUILD_STATIC=ON \
    -DCMAKE_INSTALL_PREFIX:PATH='{{third_party_dir}}' \
    '{{goobly_cache_dir}}/roaring_bitmap'
  args:
    chdir: '{{goobly_cache_dir}}/roaring_bitmap/build'
    creates: '{{goobly_cache_dir}}/roaring_bitmap/build/Makefile'

- name: Install
  shell:
    make install CXXFLAGS="-fPIC -O3" -j{{ansible_processor_vcpus}}
  args:
    chdir: '{{goobly_cache_dir}}/roaring_bitmap/build'
    creates: '{{third_party_dir}}/lib/libroaring.a'

- copy:
    dest='{{third_party_dir}}/include/roaring'
    src='{{goobly_cache_dir}}/roaring_bitmap/cpp/roaring.hh'
