---

- name: Sync soure from git
  git:
    repo='https://github.com/google/re2.git'
    accept_hostkey=yes
    clone=yes
    dest='{{goobly_cache_dir}}/libre2'
    update=yes
    recursive=yes
    version='29a8845'
    force=yes

- name: Make
  shell:
    make -j{{ansible_processor_vcpus}}
  args:
    chdir: '{{goobly_cache_dir}}/libre2'
    creates: '{{goobly_cache_dir}}/libre2/obj/libre2.a'

- name: Install
  shell:
    make install -e "prefix={{third_party_dir}}"
  args:
    chdir: '{{goobly_cache_dir}}/libre2'
    creates: '{{third_party_dir}}/lib/libre2.a'
