---

# We have this role but haven't integrated the lib yet
# - range_v3          # ranges concept library
# - linenoise_ng      # command line interactive prompt

- name: Install & build all development dependencies
  hosts: localhost
  environment: '{{ build_env }}'
  roles:
    - env
    - fastrange         # very fast hash-mod
    - gtest             # google testing
    - gflags            # flag parsing for code generator
    - glog              # logging for code generator
    - google_benchmark  # google testing
    - libboost          # utilities & needed by ALL projects
    - seastar           # futures/tasks/filesystem lib
    - flatbuffers       # serialization lib
    - xxhash            # fast hashing
    - hdrhistogram      # gil-tene's histograms
    - zstd              # compression
    - lz4               # compression
    - roaring_bitmap    # bitmap but faster than std::lib
    - libre2            # re2 cpp regex lib
