---

- name: Sync soure from git
  git:
    repo='https://github.com/google/googletest.git'
    accept_hostkey=yes
    clone=yes
    dest='{{goobly_cache_dir}}/gtest'
    update=yes
    recursive=yes
    version='247a3d8'
    force=yes

- name: configure build dir
  file: path='{{goobly_cache_dir}}/gtest/build' state=directory

- name: configure and make
  shell:
    cmake \
    -DGTEST_USE_OWN_TR1_TUPLE=0 \
    -DGTEST_HAS_PTHREAD=1 \
    -DCMAKE_INSTALL_PREFIX:PATH='{{third_party_dir}}' \
    {{goobly_cache_dir}}/gtest
  args:
    chdir: '{{goobly_cache_dir}}/gtest/build'
    creates: '{{goobly_cache_dir}}/gtest/build/Makefile'


- name: install gtest
  shell:
    "make install -j$((({{ansible_processor_vcpus}}-1))) PREFIX={{third_party_dir}}"
  args:
    chdir: '{{goobly_cache_dir}}/gtest/build'
    creates: '{{third_party_dir}}/lib64/libgtest.a'
