--

- name: Sync soure from git
  git:
    repo='https://github.com/apache/kafka.git'
    accept_hostkey=yes
    clone=yes
    dest='{{goobly_cache_dir}}/kafka'
    update=yes
    recursive=yes
    force=yes
