---

- name: Sync soure from git
  git:
    repo='https://github.com/lz4/lz4.git'
    accept_hostkey=yes
    clone=yes
    dest='{{goobly_cache_dir}}/lz4'
    update=yes
    recursive=yes
    version='ceb868f'
    force=yes

- shell: "make install -j$((({{ansible_processor_vcpus}}-1))) PREFIX='{{third_party_dir}}'"
  args:
    chdir: '{{goobly_cache_dir}}/lz4'
    creates: '{{third_party_dir}}/lib/liblz4.a'
