---

- name: install deps
  become: yes
  dnf:
    name='{{item}}'
    state=installed
  with_items:
    - uuid-devel
    - jemalloc-devel

- name: Sync soure from git
  git:
    repo='https://github.com/pmem/nvml.git'
    accept_hostkey=yes
    clone=yes
    dest='{{goobly_cache_dir}}/nvml'
    update=yes
    recursive=yes
    version='1.0'
    force=yes

- name: Compile
  command:
    make -j{{ansible_processor_vcpus}} install DESTDIR="{{third_party_dir}}" prefix=/
  args:
    chdir: '{{goobly_cache_dir}}/nvml'
    creates: '{{third_party_dir}}/lib64/libpmemlog.so'
