# Dependencies
markdown:         kramdown
highlighter:      rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jemoji']

# Permalinks
permalink:        pretty

# Setup
title:            'smf'
tagline:          'smf - **/sm…ùf/** - the fastest durable log broker in the West'
description:      ''
url:              'https://senior7515.github.io'
baseurl:          /smf/

author:
  name:           'emaxerrno'
  url:            'https://twitter.com/emaxerrno'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           'https://github.com/senior7515/smf'
